package task4_6_1;

import java.io.IOException;

public class Task4_6_1 {
    public static void main(String[] args) throws IOException {
        System.out.println("""
                Задание:\s
                Модуль 4. Наследование. Задание №6:\s
                    1. Доработайте крестики-нолики; создайте исключение, которое будете бросать при неверном
                       вводе пользователя\s

                Решение:\s""");

    }
}
